import * as yup from 'yup';
import {
  ASSEMBLING_PRICE,
  ASSEMBLING_QUANTITY,
  CASTING_PRICE,
  CASTING_QUANTITY,
  CLEANING_PRICE,
  CLEANING_QUANTITY,
  CLIENT_NAME,
  COLOR_STONES,
  DIAMOND_PRICE,
  DIAMOND_QUANTITY,
  ENGRAVING_PRICE,
  ENGRAVING_QUANTITY,
  ESTIMATE_NAME,
  FINDINGS_PRICE,
  FINDINGS_QUANTITY,
  METAL_10_PRICE,
  METAL_10_QUANTITY,
  METAL_14_PRICE,
  METAL_14_QUANTITY,
  METAL_18_PRICE,
  METAL_18_QUANTITY,
  METAL_PLATINUM_PRICE,
  METAL_PLATINUM_QUANTITY,
  METAL_SILVER_PRICE,
  METAL_SILVER_QUANTITY,
  PICTURE_PRICE,
  PICTURE_QUANTITY,
  POLISHING_PRICE,
  POLISHING_QUANTITY,
  RHODIOUM_PRICE,
  RHODIOUM_QUANTITY,
  SETTING_CENTER_STONE,
  STONE_PRICE,
  STONE_QUANTITY,
  WAX_PRICE,
  WAX_QUANTITY
} from '../../helpers/constants';

export const estimateSchema = yup.object({
  [ESTIMATE_NAME]: yup.string().required(),
  [CLIENT_NAME]: yup.string().required(),
  [WAX_PRICE]: yup.number(),
  [WAX_QUANTITY]: yup.number(),
  [CASTING_PRICE]: yup.number(),
  [CASTING_QUANTITY]: yup.number(),
  [METAL_10_PRICE]: yup.number(),
  [METAL_10_QUANTITY]: yup.number(),
  [METAL_14_PRICE]: yup.number(),
  [METAL_14_QUANTITY]: yup.number(),
  [METAL_18_PRICE]: yup.number(),
  [METAL_18_QUANTITY]: yup.number(),
  [METAL_PLATINUM_PRICE]: yup.number(),
  [METAL_PLATINUM_QUANTITY]: yup.number(),
  [METAL_SILVER_PRICE]: yup.number(),
  [METAL_SILVER_QUANTITY]: yup.number(),
  [STONE_PRICE]: yup.number(),
  [STONE_QUANTITY]: yup.number(),
  [SETTING_CENTER_STONE]: yup.number(),
  [CLEANING_PRICE]: yup.number(),
  [CLEANING_QUANTITY]: yup.number(),
  [DIAMOND_PRICE]: yup.number(),
  [DIAMOND_QUANTITY]: yup.number(),
  [COLOR_STONES]: yup.number(),
  [POLISHING_PRICE]: yup.number(),
  [POLISHING_QUANTITY]: yup.number(),
  [ASSEMBLING_PRICE]: yup.number(),
  [ASSEMBLING_QUANTITY]: yup.number(),
  [FINDINGS_PRICE]: yup.number(),
  [FINDINGS_QUANTITY]: yup.number(),
  [RHODIOUM_PRICE]: yup.number(),
  [RHODIOUM_QUANTITY]: yup.number(),
  [ENGRAVING_PRICE]: yup.number(),
  [ENGRAVING_QUANTITY]: yup.number(),
  [PICTURE_PRICE]: yup.number(),
  [PICTURE_QUANTITY]: yup.number(),
});