export const tdList = [
  {
    id: "123abc",
    rush: true,
    cad_number: "123465",
    name: "Rink Crisjon",
    created_at: '2022-02-21',
    client_job_name:  "Something",
    service: "polishing",
    description: 'Something description',
    status: "first",
    item: 'ring',
    due_date: '2022-03-21',
    done: true,
    payment_date: "",
    delivered_date: "2022-03-21",
    payment_type: 'check',
    check_number: 4456,
    delivered: true,
    final_price: 5000,
    price: "$450.00",
    client: "Alejor"
  },
  {
    id: "123abc2",
    rush: true,
    cad_number: "1234656",
    name: "Manilla",
    created_at: new Date().toISOString().split('T')[0],
    client_job_name:  "Something",
    service: "polishing",
    description: 'Something description',
    status: "first",
    item: 'ring',
    due_date: new Date().toISOString().split('T')[0],
    done: false,
    payment_date: "",
    payment_type: 'cash',
    check_number: 0,
    delivered: true,
    final_price: 5000,
    price: "$50.30",
    client: "Erika"
  },
  {
    id: "123abc3",
    rush: true,
    cad_number: "1234658",
    name: "Neck",
    created_at: new Date().toISOString().split('T')[0],
    client_job_name:  "Something",
    service: "polishing",
    description: 'Something description',
    status: "first",
    item: 'ring',
    due_date: new Date().toISOString().split('T')[0],
    done: false,
    payment_date: new Date().toISOString().split('T')[0],
    payment_type: 'cash',
    check_number: 0,
    delivered: false,
    final_price: 5000,
    price: "$0.00",
    client: "Alejor"
  },
]